# Generated by Django 5.2.3 on 2026-07-13 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Optional title for the image', max_length=200)),
                ('image', models.URLField(help_text='URL de la imagen (Cloudinary o path local).', max_length=500)),
                ('asset_folder', models.CharField(blank=True, help_text='Carpeta actual en Cloudinary (asset_folder)', max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True, help_text='Optional description')),
                ('partner', models.ForeignKey(blank=True, help_text='Partner/tienda al que pertenece esta imagen. Vacío = galería global Miluxious.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='partners.partner')),
            ],
            options={
                'verbose_name': 'Image Upload',
                'verbose_name_plural': 'Image Uploads',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
