# Generated by Django 5.2.3 on 2026-07-11 22:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Nombre público de la tienda del socio', max_length=200)),
                ('slug', models.SlugField(help_text='URL: /tiendas/<slug>/', max_length=200, unique=True)),
                ('description', models.TextField(blank=True, help_text='Descripción de la tienda del socio')),
                ('hero_image', models.ImageField(blank=True, help_text='Banner/imagen hero de la tienda del socio', null=True, upload_to='partners/hero/')),
                ('is_active', models.BooleanField(default=True, help_text='Si está activo, se muestra en el directorio')),
                ('commission_rate', models.DecimalField(decimal_places=2, default=0, help_text='Comisión sobre ventas (0-100). Postergado para payouts.', max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Partner',
                'verbose_name_plural': 'Partners',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PartnerUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('manager', 'Manager'), ('editor', 'Editor'), ('viewer', 'Viewer')], default='viewer', max_length=20)),
                ('can_manage_products', models.BooleanField(default=False, help_text='Puede crear/editar/eliminar productos')),
                ('can_manage_images', models.BooleanField(default=False, help_text='Puede subir/editar/eliminar imágenes')),
                ('can_manage_orders', models.BooleanField(default=False, help_text='Puede ver/ gestionar órdenes del partner')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='partners.partner')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Partner User',
                'verbose_name_plural': 'Partner Users',
                'ordering': ['partner', 'role'],
                'unique_together': {('user', 'partner')},
            },
        ),
    ]
