# Generated by Django 5.2.3 on 2026-07-14 21:33

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='hero_image',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Banner/imagen hero de la tienda del socio', max_length=255, null=True, verbose_name='image'),
        ),
    ]
