# Generated by Django 5.2.3 on 2026-07-02 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_socialmedia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='button_url',
            field=models.CharField(blank=True, help_text='URL a la que redirigirá el botón (puede ser absoluta o relativa, ej: /contacto o https://...)', max_length=200, verbose_name='URL del Botón'),
        ),
    ]
