# Generated by Django 5.2.3 on 2026-07-14 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_change_button_url_to_charfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='page',
            field=models.CharField(choices=[('home', 'Home'), ('tiendas', 'Tiendas')], default='home', help_text='Página en la que se mostrará este banner', max_length=20, verbose_name='Página'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='image_filename',
            field=models.CharField(help_text='Ruta relativa o URL absoluta del banner. Puede ser ruta estática (ej: banner1.jpg), ruta Cloudinary relativa (ej: v1783035210/banner.jpg) o URL completa de Cloudinary.', max_length=255, unique=True, verbose_name='Ruta/URL de la Imagen'),
        ),
    ]
