# Generated by Django 5.2.3 on 2026-07-14 22:08

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_add_banner_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Imagen del banner. Se sube directamente a Cloudinary.', max_length=255, null=True, verbose_name='image'),
        ),
    ]
