# Generated by Django 5.2.3 on 2026-07-14 22:08

from django.db import migrations


def migrate_banner_image(apps, schema_editor):
    Banner = apps.get_model('home', 'Banner')
    for banner in Banner.objects.all():
        if hasattr(banner, 'image_filename') and banner.image_filename:
            banner.image = banner.image_filename
            banner.save(update_fields=['image'])


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_banner_image_cloudinaryfield'),
    ]

    operations = [
        migrations.RunPython(migrate_banner_image, reverse_code=migrations.RunPython.noop),
    ]
