# Generated by Django 5.2.3 on 2026-07-14 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_migrate_banner_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='image_filename',
        ),
    ]
