# Generated by Django 5.2.3 on 2026-07-02 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_imageupload_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='bento_size',
            field=models.CharField(choices=[('standard', 'Standard (1x1)'), ('wide', 'Wide (2x1)'), ('tall', 'Tall (1x2)'), ('featured', 'Featured (2x2)')], default='standard', help_text='Grid size: standard (1x1), wide (2x1), tall (1x2), featured (2x2)', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.TextField(blank=True, help_text='Cloudinary URL or image path', null=True),
        ),
    ]
