# Generated by Django 5.2.3 on 2026-07-03 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_average_rating_product_review_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='bento_size',
            field=models.CharField(choices=[('standard', 'Standard (1x1)'), ('wide', 'Wide (2x1)'), ('wide-image', 'Wide image (2x1 solo imagen)'), ('tall', 'Tall (1x2)'), ('tall-image', 'Tall image (1x2 solo imagen)'), ('featured', 'Featured (2x2)'), ('hero', 'Hero (full-width)')], default='standard', help_text='Grid size: standard (1x1), wide (2x1), tall (1x2), featured (2x2)', max_length=20),
        ),
    ]
