# Generated by Django 5.2.3 on 2026-07-05 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_bento_size'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['index_order', 'name'], 'verbose_name_plural': 'categories'},
        ),
        migrations.AddField(
            model_name='category',
            name='index_order',
            field=models.PositiveIntegerField(default=0, help_text='Orden de visualización en el index/header (menor número = primero)'),
        ),
        migrations.AddField(
            model_name='category',
            name='visible_in_index',
            field=models.BooleanField(default=True, help_text='Mostrar esta categoría en el index y header'),
        ),
    ]
