# Generated by Django 5.2.3 on 2026-07-10 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_migrate_product_image_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageupload',
            name='image',
            field=models.URLField(help_text='URL de la imagen (Cloudinary o path local).', max_length=500),
        ),
    ]
