# Generated by Django 5.2.3 on 2026-07-11 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_change_imageupload_image_to_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageupload',
            name='folder_path',
            field=models.CharField(blank=True, help_text='Carpeta en Cloudinary (ej: products, gallery, products/anillo-oro)', max_length=255),
        ),
    ]
