# Generated by Django 5.2.3 on 2026-07-11 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_add_imageupload_folder_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imageupload',
            name='folder_path',
        ),
        migrations.AddField(
            model_name='imageupload',
            name='asset_folder',
            field=models.CharField(blank=True, help_text='Carpeta actual en Cloudinary (asset_folder)', max_length=255),
        ),
    ]
