# Generated by Django 5.2.3 on 2026-07-11 22:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0001_initial'),
        ('products', '0013_rename_imageupload_folder_path_to_asset_folder'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageupload',
            name='partner',
            field=models.ForeignKey(blank=True, help_text='Partner/tienda al que pertenece esta imagen. Vacío = galería global Miluxious.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='partners.partner'),
        ),
        migrations.AddField(
            model_name='product',
            name='partner',
            field=models.ForeignKey(blank=True, help_text='Partner/tienda al que pertenece este producto. Vacío = producto Miluxious (marca principal).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='partners.partner'),
        ),
    ]
