# Generated by Django 5.2.3 on 2026-07-13 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_imageupload_partner_product_partner'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImageUpload',
        ),
    ]
